### ISSUE TITLE
Internalize the app (i.e. add English language)

### ISSUE THREAD

**Issue by Xennis** [Xennis/green-walking#100]
App
- [x] Add locale and `intl` packing #97
- [x] Use `intl` for all strings add add translations #99
- [x] Geocoding: Use default language #104
- [x] Place data: Show English description, chips, ... (fallback to German with a hint mentioning that) #105 #113
- [x] Reference data privacy document in English #111 

Pipeline
- [x] Place language fields: Provide default next to language fields (e.g. `de` in Germany)? #106 #107 #108 #112

Play Store
- [x] Add and reference data privacy document in English #109 #110 
- [x] Add English Play Store listening
- [x] Add English screenshots to Play Store #116 #117

**Comment by Xennis** [comment]
Done :tada:
