### ISSUE TITLE
Add iOS support

### ISSUE THREAD

**Issue by Xennis** [Xennis/green-walking#120]
Build / CI
* [x] Run tests on MacOS #121 
* [x] Add a job to build release #122 
* [ ] Sign and Publish release

* https://medium.com/well-red/github-actions-fastlane-ios-1f6d43cce726
* https://flutter.dev/docs/deployment/ios

Adjust app

* [x] Set bundle ID and permissions #125 
* [ ] Configure Firebase #125 (config only, pod init + init code needed)
* [ ] Set logo
* [ ] Add Splash screen

App Store

* [ ] Register

**Comment by Xennis** [comment]
Currently not a focus.
